version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/image_processor
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../logs:/app/logs
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: